// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: shoe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shoe message representing a shoe product event
// Compatible with Confluent Schema Registry and Kafka serialization
type Shoe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the shoe
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Brand name of the shoe
	Brand string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	// Product name of the shoe
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Sale price of the shoe
	SalePrice float64 `protobuf:"fixed64,4,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	// Rating of the shoe (typically 1-5 scale)
	Rating        float64 `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shoe) Reset() {
	*x = Shoe{}
	mi := &file_shoe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shoe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shoe) ProtoMessage() {}

func (x *Shoe) ProtoReflect() protoreflect.Message {
	mi := &file_shoe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shoe.ProtoReflect.Descriptor instead.
func (*Shoe) Descriptor() ([]byte, []int) {
	return file_shoe_proto_rawDescGZIP(), []int{0}
}

func (x *Shoe) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shoe) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Shoe) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shoe) GetSalePrice() float64 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *Shoe) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_shoe_proto protoreflect.FileDescriptor

const file_shoe_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shoe.proto\x12\x04shoe\"w\n" +
	"\x04Shoe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sale_price\x18\x04 \x01(\x01R\tsalePrice\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06ratingB(Z&github.com/go-sarama-sr/producer/pb;pbb\x06proto3"

var (
	file_shoe_proto_rawDescOnce sync.Once
	file_shoe_proto_rawDescData []byte
)

func file_shoe_proto_rawDescGZIP() []byte {
	file_shoe_proto_rawDescOnce.Do(func() {
		file_shoe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoe_proto_rawDesc), len(file_shoe_proto_rawDesc)))
	})
	return file_shoe_proto_rawDescData
}

var file_shoe_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shoe_proto_goTypes = []any{
	(*Shoe)(nil), // 0: shoe.Shoe
}
var file_shoe_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shoe_proto_init() }
func file_shoe_proto_init() {
	if File_shoe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoe_proto_rawDesc), len(file_shoe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoe_proto_goTypes,
		DependencyIndexes: file_shoe_proto_depIdxs,
		MessageInfos:      file_shoe_proto_msgTypes,
	}.Build()
	File_shoe_proto = out.File
	file_shoe_proto_goTypes = nil
	file_shoe_proto_depIdxs = nil
}
